services:
  kiosko:
    container_name: kiosko
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - kiosko-network

networks:
  kiosko-network:
    external: true
